In [37]:
import os
os.chdir("D:\\varios\\Cursos\\Udemy_Py _Course\\numpy_intro\\")
import numpy as np


In [38]:
n = np.arange(27) #create an array of length 27 and values 0 to 26
type(n)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [39]:
#we can reshap this arr
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [40]:
#Convert list to numpy arrays object
m = np.asarray([[123,12,123,12,53],[],[]])
type(m)

numpy.ndarray

In [41]:
###
#exercise with images
import cv2
img = cv2.imread("smallgray.png",0) #0 for gray scale 1 for color scale
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [42]:
#to write image
cv2.imwrite("newsmallgray.png",img)

True

In [43]:
#to transpose
img.T

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182]], dtype=uint8)

In [44]:
#to flat the multidimentional array
help(img.flat)

Help on flatiter object:

class flatiter(builtins.object)
 |  Flat iterator object to iterate over arrays.
 |  
 |  A `flatiter` iterator is returned by ``x.flat`` for any array `x`.
 |  It allows iterating over the array as if it were a 1-D array,
 |  either in a for-loop or by calling its `next` method.
 |  
 |  Iteration is done in row-major, C-style order (the last
 |  index varying the fastest). The iterator can also be indexed using
 |  basic slicing or advanced indexing.
 |  
 |  See Also
 |  --------
 |  ndarray.flat : Return a flat iterator over an array.
 |  ndarray.flatten : Returns a flattened copy of an array.
 |  
 |  Notes
 |  -----
 |  A `flatiter` iterator can not be constructed directly from Python code
 |  by calling the `flatiter` constructor.
 |  
 |  Examples
 |  --------
 |  >>> x = np.arange(6).reshape(2, 3)
 |  >>> fl = x.flat
 |  >>> type(fl)
 |  <class 'numpy.flatiter'>
 |  >>> for item in fl:
 |  ...     print(item)
 |  ...
 |  0
 |  1
 |  2
 |  3
 |  4
 |  

In [45]:
#to stack arrays we use hstack & vstack
img2 = np.hstack((img,img,img))
print(img2)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [46]:
img3 = np.vstack((img,img,img))
print(img3)

#Note: beware for the dimentions of arrays you are trying to stack


[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [48]:
#splitting arrays
img4 = np.hsplit(img,5)
img4

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [50]:
img5 = np.vsplit(img,3)
img5

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]